// File generated by FlutterFire CLI.

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print('working web');
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  ///Firebase Config for Android

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDjsBz2VtvINOuhTI0hwbs',
    appId: '1:7368478efab06029de6c728',
    messagingSenderId: '7311569',
    projectId: 'da',
  );

  ///Firebase Config for IOS

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSywPa3sbUIZJ1vNzVNcw',
    appId: '1:731153fab06029de6c728',
    messagingSenderId: '731153469',
    projectId: 'da',
    databaseURL: 'https://.firebaseio.com',
    storageBucket: 'appspot.com',
    androidClientId: '73115343.apps.googleusercontent.com',
    iosClientId: '731153432.apps.googleusercontent.com',
    iosBundleId: 'com.RunnerTests',
  );

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'A9Kt0fZZ5JsBz2VtvINOuhTI0hwbs',
  appId: ':web:468478efab06029de6c728',
  messagingSenderId: '731153432569',
  projectId: 'table',
  databaseURL: 'https://.firebaseio.com',
  storageBucket: 'da.appspot.com',
  measurementId: 'G-',
);


}




